"""Init

Revision ID: 117a472ac724
Revises: 08f566fe29ff
Create Date: 2024-01-26 06:38:10.453391

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '117a472ac724'
down_revision: Union[str, None] = '08f566fe29ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('created_at', fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_access_token_created_at'), 'access_token', ['created_at'], unique=False)
    op.drop_index('ix_accesstoken_created_at', table_name='accesstoken')
    op.drop_table('accesstoken')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accesstoken',
    sa.Column('token', sa.VARCHAR(length=43), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('token', name='accesstoken_pkey')
    )
    op.create_index('ix_accesstoken_created_at', 'accesstoken', ['created_at'], unique=False)
    op.drop_index(op.f('ix_access_token_created_at'), table_name='access_token')
    op.drop_table('access_token')
    # ### end Alembic commands ###
